<?php

use App\Http\Controllers\Api\AnalizeController;
use App\Http\Controllers\Api\AnalizeTotalVByComponentsController;
use App\Http\Controllers\Api\BsuController;
use App\Http\Controllers\Api\CarController;
use App\Http\Controllers\Api\ClasscomponentController;
use App\Http\Controllers\Api\ClassrecipeController;
use App\Http\Controllers\Api\CompController;
use App\Http\Controllers\Api\CompmainController;
use App\Http\Controllers\Api\ConsumptioncomponentweightController;
use App\Http\Controllers\Api\CurrentcomponentweightController;
use App\Http\Controllers\Api\CustomerController;
use App\Http\Controllers\Api\DispatcherController;
use App\Http\Controllers\Api\DriverController;
use App\Http\Controllers\Api\MainstateController;
use App\Http\Controllers\Api\MixtureController;
use App\Http\Controllers\Api\OrderController;
use App\Http\Controllers\Api\OrderStateController;
use App\Http\Controllers\Api\PlantController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\ReccommentController;
use App\Http\Controllers\Api\RecfrostController;
use App\Http\Controllers\Api\RecipeController;
use App\Http\Controllers\Api\RecipedescriptionController;
use App\Http\Controllers\Api\RecipeExportController;
use App\Http\Controllers\Api\RecipestateController;
use App\Http\Controllers\Api\RecmarkaController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\RecmobilityController;
use App\Http\Controllers\Api\RecstrengthController;
use App\Http\Controllers\Api\RecwatController;
use App\Http\Controllers\Api\ReportcurrentloopController;
use App\Http\Controllers\Api\ReportweightmanualController;
use App\Http\Controllers\Api\RoleController;
use App\Http\Controllers\Api\SilcemController;
use App\Http\Controllers\Api\TtnController;
use App\Http\Controllers\Api\TtnstateController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\Api\WeightmanualController;
use Illuminate\Support\Facades\Route;

Route::post('auth/login', [AuthController::class, 'login']);
Route::post('auth/register', [AuthController::class, 'register']);
Route::post('auth/refresh', [AuthController::class, 'refresh']);
Route::post('auth/logout', [AuthController::class, 'logout'])->middleware(\App\Http\Middleware\JwtAuthenticate::class);
Route::get('auth/me', [AuthController::class, 'me'])->middleware(\App\Http\Middleware\JwtAuthenticate::class);

Route::middleware(\App\Http\Middleware\JwtAuthenticate::class)->group(function () {
    Route::apiResource('comp', CompController::class);
    Route::apiResource('bsu', BsuController::class);
    Route::apiResource('car', CarController::class);
    Route::apiResource('dispatcher', DispatcherController::class);
    Route::apiResource('customer', CustomerController::class);
    Route::apiResource('driver', DriverController::class);
    Route::apiResource('order', OrderController::class);
    Route::apiResource('mixture', MixtureController::class);
    Route::apiResource('order-state', OrderStateController::class)->only(['index', 'show', 'store']);
    Route::apiResource('class-recipe', ClassrecipeController::class);
    Route::apiResource('class-component', ClasscomponentController::class);
    Route::apiResource('comp-main', CompmainController::class);
    Route::apiResource('consumption-component-weight', ConsumptioncomponentweightController::class)->only(['index', 'show', 'store']);
    Route::apiResource('current-component-weight', CurrentcomponentweightController::class)->only(['index', 'show', 'store']);
    Route::apiResource('main-state', MainstateController::class)->only(['index', 'show', 'store']);
    Route::apiResource('plants', PlantController::class);
    Route::apiResource('product', ProductController::class)->only(['index', 'show', 'store']);
    Route::apiResource('rec-comment', ReccommentController::class);
    Route::apiResource('rec-frost', RecfrostController::class);
    Route::apiResource('recipe', RecipeController::class);
    Route::get('recipe-export', [RecipeExportController::class, 'export']);
    Route::post('recipe-import', [\App\Http\Controllers\Api\RecipeImportController::class, 'import']);
    Route::apiResource('recipe-state', RecipestateController::class)->only(['index', 'show', 'store']);
    Route::apiResource('rec-marka', RecmarkaController::class);
    Route::apiResource('rec-mobility', RecmobilityController::class);
    Route::apiResource('rec-strength', RecstrengthController::class);
    Route::apiResource('rec-wat', RecwatController::class);
    Route::apiResource('report-current-loop', ReportcurrentloopController::class)->only(['index', 'show', 'store']);
    Route::apiResource('report-weight-manual', ReportweightmanualController::class)->only(['index', 'show', 'store']);
    Route::apiResource('role', RoleController::class);
    Route::apiResource('silcem', SilcemController::class);
    Route::apiResource('ttn', TtnController::class);
    Route::post('ttn/{ttn}/publish-update', [TtnController::class, 'publishUpdate']);
    Route::apiResource('ttn-state', TtnstateController::class)->only(['index', 'show', 'store']);
    Route::apiResource('weight-manual', WeightmanualController::class);
    Route::apiResource('user', UserController::class);
    Route::apiResource('recipe-description', RecipedescriptionController::class);
    Route::get('analize-total-vproduct', [AnalizeController::class, 'analyze']);
    Route::get('analize-total-v-by-components', [AnalizeTotalVByComponentsController::class, 'analyze']);
});
